express4angular:
  image: express-4-angular:latest
  restart: always
  ports:
    - "80:3000"
  environment:
    - NODE_ENV=production
  links:
    - mongodb:mongodb

mongodb:
  image: mongo:latest
  command: mongod --smallfiles
  restart: always
  volumes:
    - /var/docker-data/express-4-angular/mongodb:/data/db